{% set name = "nnvm" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/incubator-tvm/archive/v{{ version }}.tar.gz
  sha256: 8b85b4a6ff340166a53e1dcfccdeeafbabf837f3b0a2a1cb1b2d3cc0fee771f9

build:
  number: 0
  script:
    - cd nnvm/python
    - {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py>=39 or win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - libtvm {{ version }}
    - python
    - cython
    - setuptools
    - numpy
    - pip
  run:
    - python
    - tvm-py {{ version }}
    - {{ pin_compatible('numpy') }}
    - libtvm {{ version }}

test:
  imports:
    - nnvm

about:
  home: https://tvm.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'NNVM Compiler Module of TVM Stack'
  doc_url: https://tvm.apache.org/docs/
  dev_url: https://github.com/apache/incubator-tvm

extra:
  recipe-maintainers:
    - ngam
    - marcelotrevisani
