{% set name = "nnvm" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dmlc/nnvm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fb977ec212fc812bb2edce10f37f92bfdae29a307729cd2c505baca4d02b1ab8

build:
  number: 0
  script:
    - cd python
    - {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - libtvm {{ version }}
    - dmlc
    - python
    - cython
    - setuptools
    - numpy
    - pip
  run:
    - python
    - dmlc
    - tvm-py {{ version }}
    - {{ pin_compatible('numpy') }}
    - libtvm {{ version }}

test:
  imports:
    - nnvm

about:
  home: https://tvm.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: NNVM Compiler Module of TVM Stack
  doc_url: https://tvm.apache.org/docs/
  dev_url: https://github.com/apache/incubator-tvm

extra:
  recipe-maintainers:
    - marcelotrevisani
